[project]
name = "nicegui-vscode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "brotli>=1.1.0",
    "fonttools>=4.56.0",
    "nicegui>=2.13.0",
]
